site_name: Django RESTQL
theme: readthedocs
repo_url: https://github.com/yezyilomo/django-restql/
repo_name: GitHub
site_author: Yezy Ilomo
docs_dir: docs
markdown_extensions:
    - toc:
        permalink: True

